export SPECIES=Campylobacter_jejuni
export SCHEME=$PWD/schemes/campylobacter_cgmlst_chewbbacaonline
export PRODIGAL=$CONDA_PREFIX/envs/chewiesnake/opt/chewiesnake/chewBBACA/CHEWBBACA/prodigal_training_files/$SPECIES.trn